### ISSUE TITLE
Look into how to track objects with kinect (i.e arm, bowl)

### ISSUE THREAD

**Issue by derekbelsky102** [sujaymanb/StoutREU#3]

**Comment by sujaymanb** [comment]
https://docs.opencv.org/3.1.0/d5/dae/tutorial_aruco_detection.html

**Comment by sujaymanb** [comment]
https://www.uco.es/investiga/grupos/ava/node/26
They require us to cite their papers if we use this.  For future reference.

**Comment by sujaymanb** [comment]
Video playlist for the aruco tutorials.

https://www.youtube.com/watch?v=XjJ7ujKjQQc&list=PL7EOs-8ZXfMb2qRog9wOa3Ar-EyvRYdrp&index=1&ab_channel=RafaelMu%C3%B1ozSalinas

**Comment by sujaymanb** [comment]
Finally have something working.
https://github.com/sujaymanb/KinectArTracker
